import { faker } from "@faker-js/faker";
import { sample } from "lodash";

// ----------------------------------------------------------------------

export const TABLE_HEAD = [
	{ id: "sr", label: "Sr.no", alignRight: false },
	{ id: "name", label: "Name", alignRight: false },
	{ id: "product-code", label: "Code", alignRight: false },
	{ id: "product-cost", label: "Cost", alignRight: false },
	{ id: "sale-cost", label: "Sale Cost", alignRight: false },
	{ id: "GST", label: "GST", alignRight: false },
	{ id: "location", label: "Location", alignRight: false },
	{ id: "date", label: "Date", alignRight: false },
	{ id: "stock", label: "Stock", alignRight: false },
	{ id: "company", label: "Company", alignRight: false },
	{ id: "", label: "", alignRight: false },
];

export const dummyProducts = [
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "bearing",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "screw",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "gear",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
	{
		id: "1",
		productName: "bolt",
		productCode: "ABC4623",
		productCost: 10,
		GST: 18,
		saleCost: 12,
		location: "B12",
		date: "10/01/2022",
		stock: 120,
		manufacturingCompany: {
			id: "1",
			name: "Cummings",
		},
	},
];
